from .sDetailerNode import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_DETECTOR
from .sDetailerInpaint import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_INPAINT
from .sDetailerNode import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_DETECTOR
from .sDetailerInpaint import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_INPAINT

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_DETECTOR, **NODE_CLASS_MAPPINGS_INPAINT}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS_DETECTOR, **NODE_DISPLAY_NAME_MAPPINGS_INPAINT}

print("sDetailer nodes module initialized")